# 行列と行列式

参考
* [線形代数汎論](https://amzn.asia/d/cQQdYH2)

意外と行列の定義とか用語、性質についての理解が浅いので、今回は教科書を参考に一気にやっていきましょう。


## 行列

*  代数系$K$上の$m\times n$型の行列$A=[a_{ij}] \quad (i=1, \cdots, m; j=1,\cdots, n)$の定義：
$$
A=     \begin{bmatrix}
         a_{11} & \cdots && a_{1n}\\
         \vdots & \ddots && \vdots\\ 
         a_{m1} & \cdots && a_{mn} 
     \end{bmatrix}
    ,\quad a_{ij} \in K
$$
* 下三角部分：$\{a_{ij}\mid i\geq j\}$
* 上三角部分：$\{a_{ij}\mid i\leq j\}$
* 上Hessenberg行列：$i > j+1$のとき$a_{ij}=0$
* 下Hessenberg行列：$j > i+1$のとき$a_{ij}=0$
$$
A=   \begin{bmatrix}
         a_{11} & a_{12} && \cdots &&& a_{1n}\\
         a_{21} & a_{22} && \cdots &&& a_{2n}\\ 
         0 & a_{32} && \cdots &&& a_{3n}\\ 
         \vdots & \vdots && \ddots &&& \vdots\\ 
         0 & 0 && \cdots &&& a_{mn} 
     \end{bmatrix}
    ,\quad a_{ij} \in K
$$
* 縦ベクトル：$m\times 1$型の行列
* 横ベクトル：$1\times n$型の行列

## 行列算

* 行列積：$P = [p_{ij}]=AB$なる$l \times n$型の行列
    * $p_{ij}=\sum^m_{k=1} a_{ik} b_{kj} \quad (i=1, \cdots, l; j=1, \cdots, n)$
    * ここで$A$は$l\times m$型、$B$は$m \times n$型の行列

## Hermite行列とか

* 共役：$K=\mathbb{C}$（複素数体）のとき、ca$m\times n$型の行列$A$の共役 $C=[c_{ij}]=\overline{A}$
    * $c_{ij}=\overline{a}_{ij}$で定められる$m\times n$型行列のこと。ここで$\overline{a}_{ij}$は$a$の共役複素数。 
* AのHermite共役$A^\dag$：$(\overline{A})^\top=\overline{A^\top}$
* $A$が正方行列のときの呼び方
    * $A^\top=-A$は反対称行列、交代行列、もしくは歪対称行列
    * $A^\dag=A$はHermite行列
    * $A^\dag=-A$は歪Hermite行列
* 任意の正方行列に対して$A=\frac{1}{2}(A+A^\top)+\frac{1}{2}(A-A^\top)$と対称行列と反対称行列に分割可能


## 置換行列と基本行列

* 正方行列$P$の要素がどれも$0$か$1$に等しく、どの行、列にもちょうど$1$個だけ$1$があるとき、$P$は置換行列と呼ばれる。
    * $m$次の置換行列の行$i$における$1$が列$j_i$にあるとき、$m\times n$の行列$A$に対して、$PA$の行集合の順序は$A$の行集合の順序に次の置換を施すのと同じ
    * $m$次の置換行列の行$i$における$1$が列$j_i$にあるとき、$n\times m$の行列$B$に対して、$BP$の行集合の順序は$B$の列集合の順序に次の置換を施すのと同じ
* 特に、ある$i_0$, $j_0$ ($i_0 \neq j_0$)について、$p_{ii}=1$ ($i\neq i_0, j_0$), $p_{i_0j_0}=p_{j_0i_0}-1$, $p_{i_0i_0}=p_{j_0j_0}=0$である置換行列は互換行列と呼ばれる。
    * $PA$で行$i_0$と$j_0$を入れ替える。
$$
\begin{pmatrix}
&j_1 \quad j_2 \quad \cdots \quad j_m\\
&1 \quad 2 \quad \cdots \quad m
\end{pmatrix}
$$
* 基本行列：置換行列と次の２つの行列は合わせて基本行列と呼ぶ
    * 行列$T$：$T(i_0;t)A$は$A$の行$i_0$を$t$倍する
    * 行列$W$：$W(i_0,j_0;t)A$は$A$の行$j_0$を$t$倍して行$i_0$に加える

In [16]:
import numpy as np

A = np.array([[1, 2, 3], [11, 12, 13], [21, 22, 23], [31, 32, 33]])  # 4 x 3
P = np.array([[0, 1, 0], [1, 0, 0], [0, 0, 1]])

print("置換行列")
print(P)

print(f"行列A")
print(A)
print(f"行列AP")
print(A @ P)

print(f"行列A.T")
print(A.T)
print(f"行列PA.T")
print(P @ A.T)

置換行列
[[0 1 0]
 [1 0 0]
 [0 0 1]]
行列A
[[ 1  2  3]
 [11 12 13]
 [21 22 23]
 [31 32 33]]
行列AP
[[ 2  1  3]
 [12 11 13]
 [22 21 23]
 [32 31 33]]
行列A.T
[[ 1 11 21 31]
 [ 2 12 22 32]
 [ 3 13 23 33]]
行列PA.T
[[ 2 12 22 32]
 [ 1 11 21 31]
 [ 3 13 23 33]]


## 部分行列と行列の分割

* $m\times n$型の行列$A=[a_{ij}]$の$r$本の行と$s$本の列を自然な順に配列してできる$r\times s$の行列を$A$の部分行列と言う
* ブロック行列：行列を部分行列に分割するやつ

In [26]:
import numpy as np

A = np.array([[1, 2, 3, 4], [11, 12, 13, 14], [21, 22, 23, 24], [31, 32, 33, 44]])  # 4 x 4
print("行列 A")
print(A)

sub_A = A[[1, 2]][:, [2, 3]]
print("部分行列")
print(sub_A)

行列 A
[[ 1  2  3  4]
 [11 12 13 14]
 [21 22 23 24]
 [31 32 33 44]]
部分行列
[[13 14]
 [23 24]]
